# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Github Actions Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      BASE_URL: ${{ secrets.BASE_URL }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      
jobs:
  newman:
      name: Run Newman test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@master
        - name: Use newman
          uses: matt-ball/newman-action@master
          with:
            collection: Todoist.json
            environment: QA.json
  e2eTests:
    name: Run Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v1
      - name: Create env file
        run: |
          touch .env
          echo API_ENDPOINT="https://xxx.execute-api.us-west-2.amazonaws.com" >> .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
          cat .env
      - name: Install TestCafe BrowserStack
        run: npm install testcafe-browser-provider-browserstack
      - name: Run Windows 10 Chrome@94.0 test
        uses: DevExpress/testcafe-action@latest
        with:
            args: "'browserstack:chrome@84.0:Windows 10' ./Frontend/page_model/tests"
